on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  job1:
    name: test app and build web-release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - uses: actions/setup-java@v3
      #   with:
      #     distribution: 'zulu'
      #     java-version: "12.x"
      #     cache: gradle
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Start Web Release Build
        run: flutter build web --web-renderer canvaskit  --release
      - name: Upload Web Build Files
        uses: actions/upload-artifact@v2
        with:
          name: web-release
          path: ./build/web
  job2:
    name: trasnfer web-release to server
    needs : job1
    runs-on: macos-latest
    steps:
      - name: Download Web Release
        uses: actions/download-artifact@v2
        with:
          name: web-release
      - name: Sync Files TO Demo CPANEL
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.SERVER_ID }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /
